<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Checkout\ViewModel\Checkout\AddressView\AddressListInterface;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Modal;
use Magento\Customer\Api\Data\AddressInterface;
use Magento\Customer\Api\Data\AddressSearchResultsInterface;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\Checkout\Magewire\Checkout\AddressView\ShippingDetails\AddressList as Magewire;
use Hyva\Theme\ViewModel\HeroiconsOutline;

/** @var Template $block */
/** @var ViewModelRegistry $viewModels */
/** @var Magewire $magewire */
/** @var AddressSearchResultsInterface $shippingAddressList */
/** @var AddressInterface $shippingAddress */
/** @var HeroiconsOutline $heroiconsViewModel */
/** @var Escaper $escaper */
/** @var AddressListInterface $addressList */

$addressList = $block->getData('address_list');
$addressListItems = $addressList->getAddressListItems();
$addressFormBlock = $block->getChildBlock('address-form');
?>
<div class="space-y-4">
    <?= /* @noEscape */ $block->getChildBlock($addressList->getRendererTypeAlias($addressListItems))
        ->setData('address_list', $addressList)
        ->setData('active_entity', $magewire->activeAddressEntity)
        ->toHtml()
    ?>

    <?php if ($addressFormBlock): ?>
        <?php $modal = $viewModels->require(Modal::class)
            ->createModal()
            ->withDialogRefName($addressFormBlock->getNameInLayout())
            ->withContent($addressFormBlock->toHtml())
            ->addDialogClass('w-full max-w-4xl');
        ?>

        <div x-data="hyva.modal()"
             x-on:address-form-modal-show.window="if ($event.detail.type === '<?= $escaper->escapeJs($addressList->getTypeNamespace()) ?>') {
                $dispatch('<?= /* @noEscape */ $addressList->getShowModalEvent() ?>')
             }"
             x-on:address-form-modal-hide.window="if ($event.detail.type === '<?= $escaper->escapeJs($addressList->getTypeNamespace()) ?>') {
                $dispatch('<?= /* @noEscape */ $addressList->getHideModalEvent() ?>')
             }"
             x-on:<?= /* @noEscape */ $addressList->getShowModalEvent() ?>.window="<?= /* @noEscape */ $modal->getShowJs() ?>"
             x-on:<?= /* @noEscape */ $addressList->getHideModalEvent() ?>.window="hide()"
        >
            <?= /* @noEscape */ $modal ?>
        </div>

        <?php if ($addressList->canCreateAddresses()): ?>
            <div class="bg-gray-100 p-2 rounded-b-lg space-y-2 newaddress">
                <div class="flex justify-center items-center">
                    <span class="text-sm text-gray-400 uppercase tracking-widest font-bold italic">
                        &mdash; <?= $escaper->escapeHtml(__('or')) ?> &mdash;
                    </span>
                </div>

                <button type="button"
                        wire:click="$emitTo('<?= /* @noEscape */ $addressList->getModalAddressFormBlockName() ?>', 'create')"
                        class="btn btn-secondary w-full justify-center"
                >
                    <?= $escaper->escapeHtml(__('New Address')) ?>
                </button>
            </div>
        <?php endif ?>

    <?php endif ?>
</div>
