<div class="openpos-homepage p-6">
    <div class="grid grid-cols-2 lg:grid-cols-4 gap-4">
        <img src="https://www.zero1.co.uk/media/magefan_blog/simonsays2.jpg" />
        <img src="https://www.zero1.co.uk/media/magefan_blog/hyva-platinum-partner.jpg" />
        <img src="https://www.zero1.co.uk/media/magefan_blog/barr2.jpg" />
        <img src="https://www.zero1.co.uk/media/magefan_blog/delivery-info-on-pdp.jpg" />
        <img src="https://www.zero1.co.uk/media/magefan_blog/carousels.jpg" />
        <img src="https://www.zero1.co.uk/media/magefan_blog/category-descriptions.jpg" />
        <img src="https://www.zero1.co.uk/media/magefan_blog/hyvagold.jpg" />
        <img src="https://www.zero1.co.uk/media/magefan_blog/clickandcollect.jpg" />
    </div>
</div>