<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Checkout\Block\Cart;
use Magento\Framework\Escaper;

/** @var Cart $block */
/** @var Escaper $escaper */
?>

<div class="w-full">
    <?php /* Cart items hidden as we don't need them at this point
    <div class="w-full cart-stuff hidden">
        <?= $block->getChildHtml('form_before') ?>
        <?= $block->getChildHtml('cart-items') ?>
        <?= $block->getChildHtml('checkout_cart_widget') ?>
    </div>
    */ ?>
    
    <div class="w-full cart-promos mb-4 mt-6">
        <div class="grid grid-cols-2 lg:grid-cols-4 gap-4">
            <img src="https://www.zero1.co.uk/media/magefan_blog/simonsays2.jpg" />
            <img src="https://www.zero1.co.uk/media/magefan_blog/hyva-platinum-partner.jpg" />
            <img src="https://www.zero1.co.uk/media/magefan_blog/barr2.jpg" />
            <img src="https://www.zero1.co.uk/media/magefan_blog/delivery-info-on-pdp.jpg" />
        </div>
    </div>

    <div x-data="{ showVouchers: false }" class="">
        <span class="btn btn-secondary p-6 mb-4" @click="showVouchers = !showVouchers"><?php echo _('Apply Voucher Code or Discount Code'); ?></span>
        <div class="vouchers-wrapper mt-4" x-show="showVouchers">
            <?= $block->getChildHtml('cart.discount') ?>
        </div>
    </div>

    <div class="w-full cart-summary-wrapper">
        <?= $block->getChildHtml('cart.summary') ?>
    </div>
</div>