<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Checkout\Block\Cart;
use Magento\Framework\Escaper;

/** @var Cart $block */
/** @var Escaper $escaper */
?>

<div class="w-full">
    <?php /* Cart items hidden as we don't need them at this point
    <div class="w-full cart-stuff hidden">
        <?= $block->getChildHtml('form_before') ?>
        <?= $block->getChildHtml('cart-items') ?>
        <?= $block->getChildHtml('checkout_cart_widget') ?>
    </div>
    */ ?>
    
    <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('openpos-cart-crossells')->toHtml(); ?>

    <div x-data="{ showVouchers: false }" class="">
        <span class="btn btn-secondary p-6 mb-4" @click="showVouchers = !showVouchers"><?php echo __('Apply Voucher Code or Discount Code'); ?></span>
        <div class="vouchers-wrapper mt-4" x-show="showVouchers">
            <?= $block->getChildHtml('cart.discount') ?>
        </div>
    </div>

    <div class="w-full cart-summary-wrapper">
        <?= $block->getChildHtml('cart.summary') ?>
    </div>
</div>
