<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */

/*
 * This header template is a simplified version of Magento_Theme/templates/html/header.phtml from the hyva-default theme, optimized for the checkout.
 */

?>
<div id="header"
     class="relative z-30 w-full"
>
    <div class="container flex flex-wrap items-center justify-center w-full px-6 py-3 mx-auto mt-0">
        <!--Logo-->
        <?= $block->getChildHtml('logo'); ?>
    </div>

    <!--Authentication Pop-Up-->
    <?= $block->getChildHtml('authentication-popup'); ?>
</div>

