<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
?>

<div class="border-t p-2 flex items-center justify-center bg-white">
    <span class="inline text-xs uppercase mr-1">Powered by </span>
    <img src="https://www.zero1.co.uk/media/wysiwyg/openposlogo.png" width="80px" height="12px" style="height: 12px;" class="" />
</div>