<?php
/** @var \Zero1\SubCategoryListing\Block\View $block */
?>
<?php if ($block->showSubCategoryListing()) : ?>
    <div class="sub-category-listing text-left mt-6">
		<ul>
			<?php foreach ($block->getCurrentCategoryChildren() as $currentCategoryChild) : ?>
		    	<li class="inline-flex mb-4">
		            <a class="btn btn-secondary py-4 px-6 mr-2 text-sm" href="<?php echo $block->escapeUrl($currentCategoryChild->getUrl()); ?>"><?php echo $block->escapeHtml($currentCategoryChild->getName()); ?></a>
		        </li>
			<?php endforeach; ?>
		</ul>
    </div>
<?php endif; ?>