<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Checkout\ViewModel\Navigation;
use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */
/** @var Navigation $viewModel */

$viewModel = $viewModels->require(Navigation::class);
$next = $viewModel->getConfig()->getStepAfter();
?>
<?php if ($next === null): ?>
    <button type="button"
        id="placeorderbutton"
        class="btn btn-primary c-primary-cta w-full
                disabled:opacity-10
                disabled:cursor-not-allowed"
        x-spread="buttonPlaceOrder()"
        x-bind="buttonPlaceOrder()"
    >
        <?= $escaper->escapeHtml(__('Complete Order')) ?>
    </button>
<?php endif ?>
