<?php
// @codingStandardsIgnoreFile

/** @var $block Aheadworks\Giftcard\Block\Checkout\Cart\Giftcard */
?>
<div class="w-full" x-data="awGiftCardManagement()">
    <div>
        <?php echo $block->getChildHtml('giftcard_codes') ?>
        <div id="aw_giftcard__code_info"></div>
        <form id="discount-aw-giftcard-form"
              method="post"
              class="">
            <?php echo $block->getBlockHtml('formkey')?>
            <div class="fieldset aw-giftcard">
                <div class="">
                    <div class="flex">
                        <input type="text"
                               class="w-full form-input disabled:opacity-75 disabled:bg-gray-100 disabled:pointer-events-none"
                               name="code"
                               placeholder="<?php echo $block->escapeHtml(__('Enter Gift Card code')) ?>"
                               required="required" />
                        <button class="primary btn btn-primary btn-secondary"
                                type="submit"
                                @click="onSubmitForm($event)"
                                value="<?php echo $block->escapeHtml(__('Apply Gift Card code')) ?>"
                                data-role="aw-giftcard-apply-action"
                                data-url="<?php /* @noEscape */ echo $block->escapeUrl($block->getActionUrl()) ?>">
                            <?php echo $block->escapeHtml(__('Apply Gift Card code')) ?>
                        </button>
                    </div>
                    <div class="flex">
                        <button class="btn btn-primary btn-secondary w-full mt-2"
                                type="submit"
                                value="<?php echo $block->escapeHtml(__('Check Status and Balance')) ?>"
                                data-role="aw-giftcard-check-code-action"
                                @click="onClickCheckCode($event)"
                                data-url="<?php /* @noEscape */ echo $block->escapeUrl($block->getCheckCodeUrl()) ?>">
                            <?php echo $block->escapeHtml(__('Check Status and Balance')) ?>
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

