<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Magento\LayeredNavigation\Block\Navigation;

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var Navigation $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
?>
<?php if ($block->canShowBlock()): ?>
    <div x-data="{ show: false }">
        <button 
            @click="show = !show" 
            id="pos-filter-button"
            :aria-expanded="show ? 'true' : 'false'" 
            class="btn btn-secondary text-sm py-1 px-3"
            :class="{ 'active': show }">
            Filters
        </button>
        <div x-show="show">
            <div class="border border-container bg-container-darker p-4 md:border-0 md:bg-transparent md:py-0 md:px-0 my-6"
                id="pos-layered-nav"
                x-data="initLayeredNavigation()"
                x-init="checkIsMobileResolution()"
                @resize.window.debounce="checkIsMobileResolution()"
                @visibilitychange.window.debounce="checkIsMobileResolution()"
            >
                <div class="block-title h-10 flex items-center justify-between"
                    @click="blockOpen = !blockOpen"
                >
                    <span class="text-primary text-md text-xl md:text-2xl font-semibold uppercase">
                        <?= $escaper->escapeHtml(__('Shop By')) ?>
                    </span>
                    <span class="py-1 px-1 bg-container-lighter rounded border border-container-darker hidden"
                        :class="{ 'block' : isMobile, 'hidden': !isMobile }">
                        <?= $heroicons->chevronDownHtml(
                            'transition-transform transform duration-300 ease-in-out',
                            24,
                            24,
                            [":class" => "{ 'rotate-180': blockOpen }"]
                        ); ?>
                    </span>
                </div>
                <div class="block-content filter-content pt-3 hidden md:block" :class="{ 'hidden' : isMobile && !blockOpen }">
                    <?= $block->getChildHtml('state') ?>
                    <?php foreach ($block->getFilters() as $filter): ?>
                        <?php if ($filter->getItemsCount()): ?>
                            <div class="filter-option card my-4" x-data="{ open: false }">
                                <div
                                    class="filter-options-title flex justify-between items-center cursor-pointer hover:text-secondary-darker border-container"
                                    :class="{ 'border-b pb-4': open }"
                                    @click="open = !open">
                                    <span class="title text-md md:text-lg font-semibold">
                                        <?= $escaper->escapeHtml(__($filter->getName())) ?>
                                        </span>
                                    <span class="py-1 px-1 rounded border border-container">
                                        <?= $heroicons->chevronDownHtml(
                                            'transition-transform transform duration-300 ease-in-out',
                                            24,
                                            24,
                                            [":class" => "{ 'rotate-180': open }"]
                                        ); ?>
                                    </span>
                                </div>
                                <template x-if="open">
                                    <div class="filter-options-content pt-3">
                                        <?= /* @noEscape */ $block->getChildBlock('renderer')->render($filter) ?>
                                    </div>
                                </template>
                            </div>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>
    <script>
        function initLayeredNavigation() {
            return {
                isMobile: false,
                blockOpen: false,
                checkIsMobileResolution() {
                    this.isMobile = window.matchMedia('(max-width: 767px)').matches;
                }
            }
        }
    </script>
<?php endif; ?>
