<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Checkout\Model\MethodMetaDataInterface;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Checkout\ViewModel\Checkout\Payment\MethodList as ViewModel;
use Hyva\Checkout\Magewire\Checkout\Payment\MethodList as Magewire;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magento\Quote\Api\Data\PaymentMethodInterface;

/** @var Template $block */
/** @var ViewModelRegistry $viewModels */
/** @var ViewModel $viewModel */
/** @var PaymentMethodInterface $method */
/** @var Magewire $magewire */
/** @var Escaper $escaper */
/** @var MethodMetaDataInterface $methodMetaData */

$viewModel = $viewModels->require(ViewModel::class);
$methods = $viewModel->getList();
?>
<div id="payment-methods">
    <?php if ($methods): ?>
        <div
            id="payment-method-list"
            class="space-y-2 mt-4"
            data-method="<?= $escaper->escapeHtmlAttr($magewire->method) ?>">
            <?php foreach ($methods as $method): ?>
                <?php $methodCodeAttr = $escaper->escapeHtmlAttr($method->getCode()) ?>
                <?php $methodMetaData = $viewModel->getMethodMetaData($block, $method) ?>

                <div
                    id="payment-method-option-<?= /* @noEscape */ $methodCodeAttr ?>"
                    class="border-2 rounded-md <?= $magewire->method === $method->getCode() ? 'active bg-opacity-10 border-black' : 'inactive bg-white' ?>"
                    wire:key="<?= /* @noEscape */ $methodCodeAttr ?>"
                >
                    <label class="flex gap-x-2.5 mb-0 p-4 cursor-pointer">
                        <div class="hidden">
                            <input
                                type="radio"
                                class="form-radio relative top-0.5"
                                id="payment-method-<?= /* @noEscape */ $methodCodeAttr ?>"
                                name="payment-method-option"
                                value="<?= /* @noEscape */ $methodCodeAttr ?>"
                                wire:model="method"
                            />
                        </div>

                        <span class="flex flex-1 flex-wrap justify-between gap-x-4 gap-y-2">
                            <span class="text-gray-700 font-medium flex flex-col break-words hyphens-auto leading-loose w-full text-center text-lg font-semibold">
                                <?= $escaper->escapeHtml($method->getTitle()) ?>

                                <?php if ($methodMetaData->hasSubTitle()): ?>
                                    <span class="text-gray-700 font-medium break-words hyphens-auto">
                                        <?= $escaper->escapeHtml($methodMetaData->getSubTitle()) ?>
                                    </span>
                                <?php endif ?>
                            </span>

                            <?php if ($methodMetaData->canRenderIcon() && $iconHtml = $methodMetaData->renderIcon()): ?>
                                <div>
                                    <?= /* @noEscape */ $iconHtml; ?>
                                </div>
                            <?php endif ?>
                        </span>
                    </label>
                    <?php if ($viewModel->canShowMethod($block, $method, $magewire->method)): ?>
                        <?php $html = $viewModel->getMethodBlock($block, $method)->toHtml() ?>

                        <?php if (! empty($html)): ?>
                            <div id="<?= 'payment-method-view-' . /* @noEscape */ $methodCodeAttr ?>" class="p-4 pt-0">
                                <?= /* @noEscape */ $html ?>
                            </div>
                        <?php endif ?>
                    <?php endif ?>
                </div>
            <?php endforeach ?>
        </div>
    <?php else: ?>
        <div class="message warning">
            <?= $escaper->escapeHtml(__('No Payment method available.')) ?>
        </div>
    <?php endif ?>
</div>
