<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Checkout\Model\MethodMetaDataInterface;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Checkout\ViewModel\Checkout\Payment\MethodList as ViewModel;
use Hyva\Checkout\Magewire\Checkout\Payment\MethodList as Magewire;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magento\Quote\Api\Data\PaymentMethodInterface;

/** @var Template $block */
/** @var ViewModelRegistry $viewModels */
/** @var ViewModel $viewModel */
/** @var PaymentMethodInterface $method */
/** @var Magewire $magewire */
/** @var Escaper $escaper */
/** @var MethodMetaDataInterface $methodMetaData */

$viewModel = $viewModels->require(ViewModel::class);
$methods = $viewModel->getList();
?>
<div id="payment-methods">
    <?php if ($methods): ?>
        <script>
            window.addEventListener('checkout:step:loaded', () => {
                if('<?= $escaper->escapeJs($magewire->method) ?>' && document.getElementById('payment-method-list')) {
                    window.dispatchEvent(new CustomEvent('checkout:payment:method-activate', { detail: { method: '<?= $escaper->escapeJs($magewire->method) ?>'} }))
                }
            }, { once: true })
        </script>

        <ol id="payment-method-list" class="grid w-full gap-6 md:grid-cols-2">
            <?php foreach ($methods as $method): ?>
                <?php $methodCodeAttr = $escaper->escapeHtmlAttr($method->getCode()) ?>
                <?php $methodMetaData = $viewModel->getMethodMetaData($block, $method) ?>

                <li id="payment-method-option-<?= /* @noEscape */ $methodCodeAttr ?>"
                    class="<?= $magewire->method === $method->getCode() ? 'active' : 'inactive' ?>"
                    wire:key="<?= /* @noEscape */ $methodCodeAttr ?>"
                >
                    <div class="flex gap-x-4">
                        <div class="flex items-center">
                            <input type="radio"
                                   class="flex-none disabled:opacity-25 hidden peer"
                                   id="payment-method-<?= /* @noEscape */ $methodCodeAttr ?>"
                                   name="payment-method-option"
                                   value="<?= /* @noEscape */ $methodCodeAttr ?>"
                                   wire:model="method"
                            />
                        </div>

                        <label for="payment-method-<?= /* @noEscape */ $methodCodeAttr ?>"
                         class="inline-flex items-center justify-between w-full p-5 text-black-500 bg-white border-2 border-gray-200 cursor-pointer dark:hover:text-gray-300 dark:border-gray-700 dark:peer-checked:bg-black peer-checked:text-white dark:text-gray-400 dark:bg-gray-800 dark:hover:bg-gray-700">                           
                            <div class="block">
                                <div class="w-full text-lg font-semibold"><?= $escaper->escapeHtml($method->getTitle()) ?></div>

                                <?php if ($methodMetaData->hasSubTitle()): ?>
                                    <div class="w-full">
                                        <?= $escaper->escapeHtml($methodMetaData->getSubTitle()) ?>
                                        </div>
                                <?php endif ?>
                            </div>
                        </label>





                            <?php if ($methodMetaData->canRenderIcon()): ?>
                                <div class="-mt-2.5">
                                    <?= /* @noEscape */ $methodMetaData->renderIcon() ?>
                                </div>
                            <?php endif ?>
                        </label>
                    </div>
                    <?php if ($viewModel->canShowMethod($block, $method, $magewire->method)): ?>
                        <?php $html = $viewModel->getMethodBlock($block, $method)->toHtml() ?>

                        <?php if (! empty($html)): ?>
                            <div id="<?= 'payment-method-view-' . /* @noEscape */ $methodCodeAttr ?>" class="w-full pl-8 mt-4">
                                <?= /* @noEscape */ $html ?>
                            </div>
                        <?php endif ?>
                    <?php endif ?>
                </li>
            <?php endforeach ?>
        </ol>
    <?php else: ?>
        <div class="message warning">
            <?= $escaper->escapeHtml(__('No Payment method available.')) ?>
        </div>
    <?php endif ?>
</div>
